from typing import Protocol, Any


class IModelRepository(Protocol):
    def save_model(self, model_info: dict) -> None: ...
    def fetch_model(self, model_id: str) -> dict: ...
    def fetch_models_for_ticker(self, ticker: str) -> list[dict]: ...
