from typing import Protocol, Any


class IOhlcvRepository(Protocol):
    def fetch_ohlcv(self, ticker: str, start_date: str, end_date: str) -> Any: ...
    def save_ohlcv(self, ticker: str, date: str, ohlcv: dict) -> None: ...
    def fetch_latest(self, ticker: str) -> Any: ...
