from app.bootstrap.build_settings import build_settings
from app.core.decision.recommendation_builder import (
    build_explanation as core_build_explanation,
    build_recommendation as core_build_recommendation,
)


def _get_settings(settings):
    return settings or build_settings()


def build_recommendation(payload: dict, settings=None) -> dict:
    """
    POLICY LAYER

    Input:
        - payload generated by recommender (aggregated metrics)

    Output:
        - structured trading decision (no side effects)
    """

    cfg = _get_settings(settings)
    action_labels = getattr(cfg, "ACTION_LABELS")[getattr(cfg, "LANG")]
    return core_build_recommendation(
        payload=payload,
        action_labels=action_labels,
        confidence_no_trade_threshold=getattr(cfg, "CONFIDENCE_NO_TRADE_THRESHOLD"),
        strong_confidence_threshold=getattr(cfg, "STRONG_CONFIDENCE_THRESHOLD"),
        weak_confidence_threshold=getattr(cfg, "WEAK_CONFIDENCE_THRESHOLD"),
        strong_wf_threshold=getattr(cfg, "STRONG_WF_THRESHOLD"),
    )


def build_explanation(payload: dict, decision: dict, settings=None) -> dict:
    """
    EXPLANATION LAYER

    Builds human-readable explanations (HU / EN)
    based strictly on an already finalized decision.
    """

    cfg = _get_settings(settings)
    action_labels = getattr(cfg, "ACTION_LABELS")[getattr(cfg, "LANG")]
    return core_build_explanation(
        payload=payload,
        decision=decision,
        action_labels=action_labels,
    )
